#!/bin/sh
#
# @name Drobot Hybrid
# @type Quadrotor
# @class Quadrotor x
#

# 기본 파라미터 로드 (드론 + 로버 defaults만 가져오고, VEHICLE_TYPE은 drobot으로 덮어씀)
. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/rc.rover_differential_defaults
set VEHICLE_TYPE drobot

# 시뮬레이션 설정
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=drobot}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0              # Multicopter 제어 할당 타입

# 모터 구성
param set-default CA_ROTOR_COUNT 8    # MAIN 1~4: 드론 모터, MAIN 5~8: 휠 모터
param set-default CA_SV_CS_COUNT 4    # AUX 3~6: 서보(2), 선형 액추에이터(2)

# 드론 모터 기하학적 배치 (무게중심으로부터의 각 축 방향으로의 거리, 직접 측정 후 기입해야 함)
param set-default CA_ROTOR0_PX 0.13    # PX: 무게중심으로부터 x축 방향 거리
param set-default CA_ROTOR0_PY 0.22    # PY: 무게중심으로부터 y축 방향 거리
param set-default CA_ROTOR0_KM 0.05    # KM: 모멘트 계수 (양수는 반시계방향, 음수는 시계방향 회전, 값은 일반적으로 0.05)
param set-default CA_ROTOR0_AX 0.00    # x축 방향으로 추력을 내도록 하는 연산 무시 (비행용)
param set-default CA_ROTOR0_AZ 1.00    # z축 방향으로 추력을 내도록 하는 연산만 따르도록 (비행용)

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.22
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_AX 0.00
param set-default CA_ROTOR1_AZ 1.00

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_AX 0.00
param set-default CA_ROTOR2_AZ 1.00

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.22
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR3_AX 0.00
param set-default CA_ROTOR3_AZ 1.00


# 로버 휠 모터 기하학적 배치 (무게중심으로부터의 각 축 방향으로의 거리, 직접 측정 후 기입해야 함)
param set-default CA_ROTOR4_PX 0.13
param set-default CA_ROTOR4_PY -0.20     # 왼쪽 앞바퀴
param set-default CA_ROTOR4_AX 1.00      # x축 방향으로 추력을 내도록 하는 연산만 따르도록 (주행용)
param set-default CA_ROTOR4_AZ 0.00      # z축 방향으로 추력을 내도록 하는 연산 무시 (주행용)

param set-default CA_ROTOR5_PX 0.13
param set-default CA_ROTOR5_PY 0.20     # 오른쪽 앞바퀴
param set-default CA_ROTOR5_AX 1.00
param set-default CA_ROTOR5_AZ 0.00

param set-default CA_ROTOR6_PX -0.13
param set-default CA_ROTOR6_PY -0.20     # 왼쪽	뒷바퀴
param set-default CA_ROTOR6_AX 1.00
param set-default CA_ROTOR6_AZ 0.00

param set-default CA_ROTOR7_PX -0.13
param set-default CA_ROTOR7_PY 0.20     # 오른쪽 뒷바퀴
param set-default CA_ROTOR7_AX 1.00
param set-default CA_ROTOR7_AZ 0.00


# 서보 및 액추에이터 할당
# SV: 드론 암 관절 서보 (접기/펴기)
param set-default CA_SV_CS0_TYPE 12     # 커스텀 타입
param set-default CA_SV_CS1_TYPE 12
param set-default CA_SV_CS2_TYPE 12
param set-default CA_SV_CS3_TYPE 12


# 시뮬레이션: 전원 체크 바이패스
param set-default CBRK_SUPPLY_CHK 894281

# 시뮬레이션 매핑 (Gazebo와 연동)
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

# ===== PWM Timer Rate =====
# MAIN 1~4: 드론 모터 400Hz
param set-default PWM_MAIN_TIM0 400
# MAIN 5~8: 로버 모터 50Hz
param set-default PWM_MAIN_TIM1 50
# AUX 1~4: 변신 서보 50Hz
param set-default PWM_AUX_TIM0 50
